name: app
description: "Cashier App."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  http: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  flutter_dotenv: ^5.1.0
  blue_thermal_printer: ^1.2.3
  barcode_scan2: ^4.3.0
  fl_chart: ^0.66.2
  vibration: ^1.8.4
  share_plus: ^7.2.2
  excel: ^4.0.2
  screenshot: ^2.1.0
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  get: ^4.6.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/sound/
    - assets/fonts/
